apiVersion: skaffold/v2beta6
kind: Config
build:
  artifacts:
  - image: uk.icr.io/prometeo-cluster/ws
deploy:
  helm:
    releases:
    - name: ws
      chartPath: chart/ws
      artifactOverrides:
        mqttclient:
          image:
            repository: uk.icr.io/prometeo-cluster/ws