{{ if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometeo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{ end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometeo-ws
spec:
  hosts:
  - "*"
  gateways:
  - prometeo-gateway
  http:
  - match:
    - uri:
        exact: /ws
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Values.ws.name}}
        port:
          number: {{ .Values.ws.service.servicePort}}
    route:
    - destination:
        host: {{ .Values.ws.name}}
        port:
          number: {{ .Values.ws.service.servicePort}}
